language: julia
julia:
    - nightly
install:
    - git fetch --unshallow
    - julia -e 'Pkg.clone(pwd())'
script:
    - julia --check-bounds=yes --inline=no -e 'Pkg.test("Jumos", coverage=true)'
after_success:
    - julia -e 'cd(Pkg.dir("Jumos")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
sudo: false
